# Generated by Django 6.0.1 on 2026-07-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarhall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hall_images/'),
        ),
    ]
